### ISSUE TITLE
Hash verification fails due to incorrect path in borderwallets.txt

### ISSUE THREAD

**Issue by blackcoffeexbt** [microchad/borderwallets#4]
The path to the html file in borderwallets.txt is ./dist/borderwallets.html in the latest release. This gives an error when running

`shasum --check borderwallets.txt`

![image](https://user-images.githubusercontent.com/87530449/183072590-30e12bd8-293d-4a5e-a8bf-4401e80e34cd.png)

Changing the file path in borderwallets.txt from

`./dist/borderwallets.html`

to 

`borderwallets.html`

Will fix this issue.

**Comment by SuperPhatArrow** [comment]
Fixed in v1.0.5

Thanks for the report
